---
- name: WP Project EKS Configuration
  hosts: localhost
  gather_facts: False
  become: False

  pre_tasks:
    - name: EKS Configuration
      debug:
        msg: "Configuring EKS Cluster for WP"
      
  roles:
    - eks-addon-config
    - eso-config
    - bitnami-wordpress-install


    



    


        


        
